ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjUwOTA1MzUyOC4xNzQ3MjAzNTczIn0sImFub25JZCI6ImFjNDIwMmU4Zjc1N2I5ZjIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouZGUvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvdmFuL21hcmNvLXBvbG8vb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjM0MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI1ODA3MzQwNTU2NTQzMzIzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x560d2239875a <unknown>
#1 0x560d21e4b4b0 <unknown>
#2 0x560d21e31d86 <unknown>
#3 0x560d21e3069a <unknown>
#4 0x560d21e30dff <unknown>
#5 0x560d21e30d54 <unknown>
#6 0x560d21e4f69f <unknown>
#7 0x560d21ef492a <unknown>
#8 0x560d21ec2592 <unknown>
#9 0x560d21ee85e0 <unknown>
#10 0x560d21ec2363 <unknown>
#11 0x560d21e8ed63 <unknown>
#12 0x560d21e8f9c1 <unknown>
#13 0x560d2235da6b <unknown>
#14 0x560d22361951 <unknown>
#15 0x560d22345b62 <unknown>
#16 0x560d223624c4 <unknown>
#17 0x560d2232a13f <unknown>
#18 0x560d223866f8 <unknown>
#19 0x560d223868d6 <unknown>
#20 0x560d223975a6 <unknown>
#21 0x7f7f9f69caa4 <unknown>
#22 0x7f7f9f729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwiY29udGVudFpvbmVzIjpbXSwidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5kZS9wYXNzZW5nZXJjYXJzL21vZGVscy92YW4vbWFyY28tcG9sby9vdmVydmlldy5odG1sP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiMzQxIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI1MDkwNTM1MjguMTc0NzIwMzU3MyJ9LCJhbm9uSWQiOiJhYzQyMDJlOGY3NTdiOWYyIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6M30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA3NjkwMzU0Njk0NTg1MTY2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x560d2239875a <unknown>
#1 0x560d21e4b4b0 <unknown>
#2 0x560d21e31d86 <unknown>
#3 0x560d21e3069a <unknown>
#4 0x560d21e30dff <unknown>
#5 0x560d21e30d54 <unknown>
#6 0x560d21e4f69f <unknown>
#7 0x560d21ef492a <unknown>
#8 0x560d21ec2592 <unknown>
#9 0x560d21ee85e0 <unknown>
#10 0x560d21ec2363 <unknown>
#11 0x560d21e8ed63 <unknown>
#12 0x560d21e8f9c1 <unknown>
#13 0x560d2235da6b <unknown>
#14 0x560d22361951 <unknown>
#15 0x560d22345b62 <unknown>
#16 0x560d223624c4 <unknown>
#17 0x560d2232a13f <unknown>
#18 0x560d223866f8 <unknown>
#19 0x560d223868d6 <unknown>
#20 0x560d223975a6 <unknown>
#21 0x7f7f9f69caa4 <unknown>
#22 0x7f7f9f729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure-Vans/QA-App-Allure-Vans/Tests/BFV1_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message:
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwiY29udGVudFpvbmVzIjpbXSwidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5kZS9wYXNzZW5nZXJjYXJzL21vZGVscy92YW4vbWFyY28tcG9sby9vdmVydmlldy5odG1sP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiMzQxIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNTY0Nzc5MTYwLjE3NDcyMDM2MjEifSwiYW5vbklkIjoiMDIxZTljYmZlZDlmMzViMCJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjExMDE5NTk1NDgwNjk4NTUyIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5647ac8f175a <unknown>
#1 0x5647ac3a44b0 <unknown>
#2 0x5647ac38ad86 <unknown>
#3 0x5647ac38969a <unknown>
#4 0x5647ac389dff <unknown>
#5 0x5647ac389d54 <unknown>
#6 0x5647ac3a869f <unknown>
#7 0x5647ac44d92a <unknown>
#8 0x5647ac41b592 <unknown>
#9 0x5647ac4415e0 <unknown>
#10 0x5647ac41b363 <unknown>
#11 0x5647ac3e7d63 <unknown>
#12 0x5647ac3e89c1 <unknown>
#13 0x5647ac8b6a6b <unknown>
#14 0x5647ac8ba951 <unknown>
#15 0x5647ac89eb62 <unknown>
#16 0x5647ac8bb4c4 <unknown>
#17 0x5647ac88313f <unknown>
#18 0x5647ac8df6f8 <unknown>
#19 0x5647ac8df8d6 <unknown>
#20 0x5647ac8f05a6 <unknown>
#21 0x7f811349caa4 <unknown>
#22 0x7f8113529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NjQ3NzkxNjAuMTc0NzIwMzYyMSJ9LCJhbm9uSWQiOiIwMjFlOWNiZmVkOWYzNWIwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmRlL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3Zhbi9tYXJjby1wb2xvL292ZXJ2aWV3Lmh0bWw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiIzNDEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2Njk1OTA0OTM1OTE4ODA1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5647ac8f175a <unknown>
#1 0x5647ac3a44b0 <unknown>
#2 0x5647ac38ad86 <unknown>
#3 0x5647ac38969a <unknown>
#4 0x5647ac389dff <unknown>
#5 0x5647ac389d54 <unknown>
#6 0x5647ac3a869f <unknown>
#7 0x5647ac44d92a <unknown>
#8 0x5647ac41b592 <unknown>
#9 0x5647ac4415e0 <unknown>
#10 0x5647ac41b363 <unknown>
#11 0x5647ac3e7d63 <unknown>
#12 0x5647ac3e89c1 <unknown>
#13 0x5647ac8b6a6b <unknown>
#14 0x5647ac8ba951 <unknown>
#15 0x5647ac89eb62 <unknown>
#16 0x5647ac8bb4c4 <unknown>
#17 0x5647ac88313f <unknown>
#18 0x5647ac8df6f8 <unknown>
#19 0x5647ac8df8d6 <unknown>
#20 0x5647ac8f05a6 <unknown>
#21 0x7f811349caa4 <unknown>
#22 0x7f8113529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure-Vans/QA-App-Allure-Vans/Tests/BFV1_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: